### ISSUE TITLE
TAB Key broken in 0.9.3a  

### ISSUE THREAD

**Issue by CodaCodr** [clientside/amplesdk#10]
Cannot use tab key to move focus between focusable elements.  Problem resides in Ample runtime(-dev).js file.

Platform(s) : Firefox 3.6.3 and IE 7.0.6000.xxxx, Win Vista SP1, AmpleSDK 0.9.3a 

See: http://groups.google.com/group/amplesdk/browse_thread/thread/911bc0e5817bf1c5

**Comment by CodaCodr** [comment]
It's "browser-firefox" too.

**Comment by clientside** [comment]
Please provide a testcase. Seem to be working in master.

**Comment by CodaCodr** [comment]
The link I provided contains the test case.

**Comment by CodaCodr** [comment]
Test failed in Firefox 4b6 too.

Is this issue Closed?

**Comment by clientside** [comment]
I looked into test case and figured out that content is not wrapped with script tags. In an Ample SDK application focus outside Ample SDK content will not work - our focus manager takes over the page entirely.

**Comment by clientside** [comment]
Sorry for issue closed prematurely. Now it should be closed based on previous comment.

**Comment by CodaCodr** [comment]
You realise that:
  [script type="text/javascript" src="runtime.js"][/script]

will break a previously working page?

If Ample focus manager "takes over the page entirely" then it has the honour bound duty to support controls anywhere on the entirety of the page (whether or not they are inside ample.close/open or not).  Said the other way, if Ample needs to be told where (via ample.open) then it should not assume "everywhere".

You really cannot have it both ways, guys.

I think Sergey said it best when he said Ample focus manager might be a bit too greedy.  Indeed!
