### ISSUE TITLE
insertAfter() and after() throw exception

### ISSUE THREAD

**Issue by tedbeer** [clientside/amplesdk#103]
test fragment (you can run it in the sandbox):

`<ul xmlns="http://www.w3.org/1999/xhtml"><li>aaa</li><li>bbb</li></ul>`

the following code should leave nodes at the same place but it throws exception:

`var items = ample.query('ul')[0].childNodes;
 ample.query(items[1]).insertAfter(items[0])`

using **after** also fails:

`var items = ample.query('ul')[0].childNodes;
 ample.query(items[0]).after(items[1])`

Similar code using **before()/insertBefore()** works correctly.

**Comment by tedbeer** [comment]
ample.query().prependTo() also fails if an element is already in place

**Comment by ilinsky** [comment]
Please provide test script for prependTo

**Comment by ilinsky** [comment]
Fixed in commit f04c63ac74
