### ISSUE TITLE
XUL: Overlay element is not implemented.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#104]
Overlays allow parts of the UI to be loaded dynamically at runtime.   For example, menu items can be inserted into menus after the menus have been built, elements can be added to boxes or decks, all through id matching.

document.loadOverlay(url, observer) is part of XUL; a function as described here:
https://developer.mozilla.org/en/DOM/document.loadOverlay

It is different from XInclude because it allows parts of the UI to be loaded dynamically at runtime.

Currently, documentation about overlays has been greyed out of the reference.  loadOverlay exists in reference/books/ample/xul/XULDocument.xml but has been commented out.  Other than that reference, a grep of the ample repos for 'overlay' or 'loadOverlay' comes up with nothing else.

**Comment by h6w** [comment]
I think document.loadOverlay may actually be implemented by combining ample.get() and passing the result to ample.importNode().

**Comment by ilinsky** [comment]
Committed skeleton for implementation of loadOverlay and xul-overlay PI in commits ff10710f1a and 641a63632f

**Comment by h6w** [comment]
Overlay processing implemented (without special processing instruction) in h6w overlay branch.  Just some things to discuss with ilinsky before submitting a pull request.
1) Storing all loaded overlays.
2) Bug regarding removal of elements not resulting in reflow.
3) Bug regarding error thrown relating to mouse movement after elements removed.

**Comment by h6w** [comment]
Pull request submitted. From previous post, solved (1), but not (2) or (3).

**Comment by h6w** [comment]
Oh, and observers and the processing instruction not implemented yet.

**Comment by ilinsky** [comment]
Fixed per rev a1a0f455066650471745faa4a5b12508e00bc00a
