### ISSUE TITLE
 xul:toolbarbutton down arrow clickability issue 

### ISSUE THREAD

**Issue by CodaCodr** [clientside/amplesdk#11]
It seems to me that the capture area for the down-arrow section of a
xul:toolbarbutton (type="menu-button") is too small - it seems to be
bounded by the GIF image (toolbarbutton_arrow.gif) instead of the
implied area of the divided section within the button.  Unless I click
the image, or very close to it, the menu does not drop down.

You can see this behaviour in the XUL Toolbar demo code supplied with
Ample.

**Comment by clientside** [comment]
Fixed in commit 282eb2f (the clickable area is bigger in height now). The button will be re-implemented anyway later on.
