### ISSUE TITLE
XUL: key tag ignores oncommand attribute

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#113]
For some reason, the key tag will work if you specify another command, but not directly with the oncommand attribute.
So:
&lt;command id="mycommand" oncommand="alert('Hallo!');" /&gt;
&lt;key id="mykey" key="U+004C" command="mycommand" /&gt;
Works, but
&lt;key id="mykey" key="U+004C"  oncommand="alert('Hallo!');" /&gt;
doesn't.

**Comment by ilinsky** [comment]
Fixed per commit 59bdf13
