### ISSUE TITLE
Key identifiers don't match

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#114]
I'm using XUL as an example, but I don't think it's limited to XUL.

If I do:
&lt;key id="mykey" key="l" command="mycommand" /&gt;
Nothing happens when I press the L key.

Upon debugging, at https://github.com/clientside/amplesdk/blob/master/ample/languages/xul/elements/key.js#L31 oEvent.keyIdentifier is 'U+004C' which means that the test will succeed at that line and the function will return without running the command.

I don't know if the keyIdentifier in the event should be translated to 'L' or if the key attribute should be translated to U+004C, but either way would work.  They just have to match.

This was testing in Google Chrome.  I haven't tested this in other browsers, so that may have an effect on the decision, particularly if not all browsers are returning the same keycodes.

**Comment by ilinsky** [comment]
Fixed per rev e719e23f1106b415abdc64301a1e858005ac6493
