### ISSUE TITLE
XUL: elements with VIEW_TYPE_VIRTUAL inside page are given visual space

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#115]
In this example on Chrome:
http://pastebin.com/7qnEwJ3f

The label "test" and the window are both shifted down because the commandset and keyset elements create space.

If one removes the commandset and keyset elements, the label moves to the top.

For some reason there is also additional vertical space between the label and window that I can't account for, and a margin left and top as well that doesn't appear to be specified anywhere.

By my reckoning, none of this space should exist.  Why is it appearing?

**Comment by ilinsky** [comment]
First of all window element cannot be tested in page element. Put elements as siblings and problem will be gone.
