### ISSUE TITLE
@ operator in XUL-manipulating javascript

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#119]
I came across this snippet of code in XULGear:

<code>treeitem.treerow.treecell[0].@label = "[#text]";</code>

According to wikipedia "In certain JavaScript implementations, the at sign (@) can be used in an identifier, this is contrary to the specifications and not supported in newer implementations."

I believe that, in this case, it is actually shorthand for:

<code>treeitem.treerow.treecell[0].setAttribute('label',"[#text]");</code>

I have also seen it used like:
<code>var label = treeitem.treerow.treecell[0].@label;</code>
meaning:
<code>var label = treeitem.treerow.treecell[0].getAttribute('label');</code>

Is there any way we can support such shorthand?

**Comment by h6w** [comment]
I suppose we could either do it in javascript, or by preprocessing all javascript using PHP.

My guess would be that the PHP option would be quicker and faster to implement and require less client overhead.  However, obviously that places some load on the server, and we'd also need to feed the PHP code details about the browser to get the versioning right.

**Comment by ilinsky** [comment]
The syntax highlighted is E4X language. scripting language processot is beyond the scope of Ample SDK. Will not be implemented.
