### ISSUE TITLE
DTDs referenced in XML files are ignored, resulting in missing entities in Chrome

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#121]
According to the network report in Chrome, DOMParser fails to call SYSTEM DTDs specified with:
<!DOCTYPE rootname SYSTEM "filename">

DTDs can contain entity definitions (such as language translations).  Failure to load the DTD causes Chrome's DOMParser to fail the well-formed test due to "unknown entities".

For an example of this, see:
https://github.com/clientside/amplesdk/blob/master/examples/applications/xulgear/src/chrome/content/xulgear.xul
and the corresponding DTD for english:
https://github.com/clientside/amplesdk/blob/master/examples/applications/xulgear/src/locale/en-US/translations.dtd

**Comment by h6w** [comment]
Interestingly, use of external DTDs as referenced in W3Schools (see http://www.w3schools.com/dtd/dtd_intro.asp) have been listed as "optional" in the XML spec.

However, FF uses them heavily in XUL apps, so I think we should develop a workaround for entities, at least.

**Comment by ilinsky** [comment]
Fixed per rev 65e1219fc28b4c15289f915557c31fc75bfb5717 
Test case: https://github.com/clientside/amplesdk-tests/tree/master/manual/issues/121
