### ISSUE TITLE
Support for Array Comprehentions from Javascript 1.7

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#122]
Features like Array comprehensions from Javascript 1.7 are trivial to implement using a javascript preprocessor.

For example:
<code>var evens = [i for each (i in range(0, 21)) if (i % 2 == 0)];</code>
would become:
<code>
var evens = [];  
for (var i=0; i <= 20; i++) {  
  if (i % 2 == 0)  
    evens.push(i);  
}
</code>
For browsers lacking JS1.7 support.  (e.g. WebKit)

Lots of this code exists in the form of XUL applications, because XUL's primary execution environment is Firefox which supports JS 1.7.  Small amounts of preprocessing would make porting XUL code much easier.

**Comment by ilinsky** [comment]
Ample SDK does not leverage javascript processor, so there is no way to enable new JS semantics.
