### ISSUE TITLE
0.9.3 from website is different from 0.9.3 tag from github

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#123]
As an example, compare examples/applications/imclient/index.html in the file "ample-0.9.3.zip" to the file provided by github under the '0.9.3' tag here:

https://github.com/clientside/amplesdk/blob/c400e9b3645297ba5bd02c66b530f85cfe69cd6f/examples/applications/imclient/index.html

I think it's time to release another version.  It's 2012 already, anyway, so time to update the copyright notices.

**Comment by h6w** [comment]
I also compared the tarball download from github with the website download and it's hugely different.

**Comment by ilinsky** [comment]
Please note, the tar available for download from github is a snapshot of source tree. The download available at www.amplesdk.com is a build version. Many source files get mofified/optimized when build. It is not always possible to run source examples with build framework and vice versa.

As for XUL dynamic tree creation, please open new issue.
