### ISSUE TITLE
XUL:Scrollbox does not appear when overflow:auto is used.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#124]
I notice that scrollbox is disabled, so I looked at MDN and they discourage use of it anyway.

According to MDN https://developer.mozilla.org/en/XUL/scrollbox :
"If you just want scrollbars to appear, add style='overflow: auto;'. This may also be used with any other container element."

However, this does not work.  No such scrollbox appears under these conditions.  See this example: http://pastebin.com/LfYnGkCm

**Comment by ilinsky** [comment]
Fixed scrollbox element per rev 94f41e021a845960e11439358b2d369546fe7543 Now it has scroll arrows appearing automatically. overflow:auto on arbitrary element cannot be enabled at this point.
