### ISSUE TITLE
Chrome: event.layerX and event.layerY are broken and deprecated in WebKit.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#128]
Running ample in chrome results in the following warning in the console:
event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.

This appears to be released every time the mouse moves!

**Comment by ilinsky** [comment]
There is no usage of layerX/layerY in Ample SDK code. Messages you observe may be caused by some extension you use?

**Comment by h6w** [comment]
Nice catch.  I didn't think I had any plugins in Chrome.  Turns out it 
was cubbi.es
