### ISSUE TITLE
XUL examples do not work in Firefox 4b6

### ISSUE THREAD

**Issue by clientside** [clientside/amplesdk#13]
parse error displayed http://www.amplesdk.com/examples/markup/xul/views/

**Comment by CodaCodr** [comment]
Easy fix - just make sure you add the Remote XUL Manager and configure it (in this case for www.amplesdk.com)
https://addons.mozilla.org/en-US/firefox/addon/235281/

Russ

**Comment by ilinsky** [comment]
Reported issue https://bugzilla.mozilla.org/show_bug.cgi?id=606697

**Comment by ilinsky** [comment]
Nice, the referenced issue is now closed with WONTFIX status.

**Comment by clientside** [comment]
Implemented workaround, available in http://github.com/clientside/amplesdk/commit/f477a3a8bb628affc89499afac5f375ab2b94d46
