### ISSUE TITLE
setting open attribute of treeitem causes TypeError

### ISSUE THREAD

**Issue by sergeev-av** [clientside/amplesdk#141]
Setting open attribute of xul:treeitem before adding any row throws TypeError. There is no check for null in treeitem.js(line 104).

Example:
var item = ample.createElementNS( sXulNS, "xul:treeitem" );
to.appendChild( item ); 
if ( itemData.isFolder )
{
    item.setAttribute( "open", "false" ); // this line causes TypeError
    item.setAttribute( "container", "true" );
    item.onclick = loadItems;
}
var row = ample.createElementNS( sXulNS, "xul:treerow" );
var cell = ample.createElementNS( sXulNS, "xul:treecell" );
cell.setAttribute( "label", itemData.name );
row.appendChild( cell );  
cell = ample.createElementNS( sXulNS, "xul:treecell" );
cell.setAttribute( "label", "Download" );
row.appendChild( cell );  
item.appendChild( row ); // <-row is added here

**Comment by ilinsky** [comment]
Fixed per rev 0a8aad663bcedba5ea6beb0d7af6365bbd9e08ac
