### ISSUE TITLE
 dynamically added tree item appears in wrong place

### ISSUE THREAD

**Issue by sergeev-av** [clientside/amplesdk#142]
Steps:
1) adding items to empry tree. Folder1(open=false, container=true), Folder2(open=false, container=true), File1(container=true).
2) clicked Folder1 loads items in itself. Same folders, files, same parameters.
3) loaded items appear under File1 item

Expected behaviour: loaded items should appear under Folder1, inside Folder1.

Here is an example: http://pastebin.com/z0q5bb96

**Comment by ilinsky** [comment]
Fixed per rev 48ee48226acf862e4092c0159795e3d229bef65c
