### ISSUE TITLE
TypeError during treechildren load

### ISSUE THREAD

**Issue by sergeev-av** [clientside/amplesdk#144]
I tried to load treechildren into treeitem using query.load. TypeError was thrown.

Main page: http://pastebin.ru/tP86tfOJ
Loading resource: http://pastebin.ru/P9ASSaPl

**Comment by ilinsky** [comment]
Partially fixed per rev f08e57eb0d0d4f47e56e4e2f60cf913b802cf1f5 A side effect to address (now tree's items collection does not populate when modifying tree by script)

Please also note, that ample.load() function replaces entire contents of the element. See how to append loaded content: https://github.com/clientside/amplesdk-tests/blob/master/manual/issues/144/index.html

**Comment by sergeev-av** [comment]
Replacement of entire content is expected behaviour. But reference says "Loads data from the server and apends it to the first element in colection".

**Comment by ilinsky** [comment]
Fixed per rev bb57555f0db4425a0ccff5af6d04425b954decc0
