### ISSUE TITLE
conflicts between ample.query show/hide methods and @style

### ISSUE THREAD

**Issue by tedbeer** [clientside/amplesdk#146]
In the following test the DIV element will remain visible but must not.
The last statement does not update HTML element style because after .show() is finished we have a conflict:
the DIV element has style set to 'display:none' but its html presentation - does not.
## The test:

&lt;div xmlns="http://www.w3.org/1999/xhtml" onclick="
this.setAttribute('style', 'display:none');
ample.query(this).show('slow');
this.setAttribute('style', 'display:none');
">XXXXXXXXXXXXX&lt;/div>

**Comment by tedbeer** [comment]
Sorry the example is not correct. The last statement must be called in .setTimeout for example after the element is shown. But the issue is relevant - it does not work either.

**Comment by ilinsky** [comment]
Fixed per rev 51cc20ea0c03284856ad46de3b36019e903e714b
