### ISSUE TITLE
XUL:observes missing

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#148]
The XUL:observes tag is not implemented.  It is described here: https://developer.mozilla.org/en-US/docs/XUL/observes
and says:
The observes element can be used to listen to a broadcaster and receive events and attributes from it. The observes element should be placed inside the element that wants to observe the broadcaster. When an observed attribute is modified on the broadcaster, the attribute's value will be forwarded and set on the parent element of the observer.

Here is a tutorial on its use:
https://developer.mozilla.org/en-US/docs/XUL_Tutorial/Broadcasters_and_Observers

Currently, upon use, ample returns:
Element "xul:observes" definition is missing from "http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" namespace. Element processing skipped

The "observes" attribute is currently defined and working, so the difference will be a new tag and implementation of the "onbroadcast" signal.

**Comment by h6w** [comment]
I have submit a pull request to resolve this.

**Comment by ilinsky** [comment]
I have a question: what for are 2 lines starting https://github.com/clientside/amplesdk/blob/master/ample/languages/xul/elements/broadcaster.js#L36 ? The test for onbroadcast property on the instance of element does not catch the presence of all types of handlers possibly attached to the element or somewhere amongst its ancestors. Please explain.

**Comment by ilinsky** [comment]
I have rectified some of your code. Please check commits 19488d4307728a04aabd40d0f81bf8bb51584f71 and 5728d38d2fe28c7e3eede8e547f4de8ba5efcc6e

**Comment by h6w** [comment]
Done.  Looks ok.  Thanks.
