### ISSUE TITLE
Query.load() ignores the callback

### ISSUE THREAD

**Issue by AmicaNoctis** [clientside/amplesdk#154]
var query = ample.query(someQueryString);
query.load(uri, data, callback) doesn't invoke the callback when the request has finished.

Meanwhile you may use this workaround for requests with valid XML response:

var query = ample.query(someQueryString);
ample.get(someUri, someData, function (document) {
    query[0].appendChild(ample.importNode(document.documentElement, true));
});

--Amica

**Comment by ilinsky** [comment]
Fixed per rev 2656ec961e7993ac32439f63d4c1f020c962f18a The reason this never came up is probably because developers were using onload/onerror event handlers picked on elements being loaded, rather than callback function passed with function call.
