### ISSUE TITLE
Error in ample.classes.CharacterData.prototype.deleteData()

### ISSUE THREAD

**Issue by AmicaNoctis** [clientside/amplesdk#158]
The offset and count parameters are handled incorrectly. Below is a FireBug console session of a page running Ample SDK (revision https://github.com/clientside/amplesdk/commit/f3c39a023857a5d8cf63d387b2a2f02f81d8f86e):

> > > var someText = ample.documentElement.appendChild(ample.createTextNode("Hello World"));
> > > undefined
> > > 
> > > someText.data
> > > "Hello World"
> > > 
> > > someText.nodeValue
> > > "Hello World"
> > > 
> > > someText.deleteData(9, 1)
> > > undefined
> > > 
> > > someText.nodeValue
> > > "Hello Worl" (EXPECTED "Hello Word")
> > > 
> > > someText.deleteData(0, 4)
> > > undefined
> > > 
> > > someText.nodeValue
> > > "Hell" (EXPECTED "o Word")

On a page not running Ample and just using Firefox's native implementation the results are correct according to W3C:

> > > var ample = document;
> > > undefined
> > > 
> > > var someText = ample.documentElement.appendChild(ample.createTextNode("Hello World"));
> > > undefined
> > > 
> > > someText.data
> > > "Hello World"
> > > 
> > > someText.nodeValue
> > > "Hello World"
> > > 
> > > someText.deleteData(9, 1)
> > > undefined
> > > 
> > > someText.nodeValue
> > > "Hello Word"
> > > 
> > > someText.deleteData(0, 4)
> > > undefined
> > > 
> > > someText.nodeValue
> > > "o Word"

In the source file CharacterData.js line 43 is written:
    oNode.data      = oNode.data.substring(0, nOffset) + oNode.data.substring(nOffset, nOffset + nLength);

However, it must be
    oNode.data      = oNode.data.substring(0, nOffset) + oNode.data.substring(nOffset + nLength, sValueOld.length);

Cheers,

Amica

**Comment by ilinsky** [comment]
Thanks, Amica. Applied your fix in rev c133448c1a27476d2d80935fd0a6627eb09e86a7
