### ISSUE TITLE
Error in ample.classes.Node.prototype.compareDocumentPosition()

### ISSUE THREAD

**Issue by AmicaNoctis** [clientside/amplesdk#160]
Suppose, we have the following XML document:
<parent>
  <child />
  <child />
  <last-child />
</foo>

lastChild.compareDocumentPosition() will always return 1 (DOCUMENT_POSITION_DISCONNECTED) for any other child, but it should return 2 (DOCUMENT_POSITION_PRECEDING).

Solution:
In ample/runtime/classes/core/Node.js line 435 the comment is correct but the return value must be 2, not 1.

Regards,

Amica

**Comment by ilinsky** [comment]
Fixed per rev 386b1e994ae389f64bfdac07d18069363f33d377 Was typo introduced while changing use of constants to constant values..
