### ISSUE TITLE
Replacing node with same ID

### ISSUE THREAD

**Issue by sergeev-av** [clientside/amplesdk#171]
I try to replace node with same ID using "Query.replaceWith".  It says 'Duplicate ID attribute value "list" used'. 

Example: http://pastebin.com/XKYaDJ2M
Annex:  http://pastebin.com/sBjMm19D

**Comment by ilinsky** [comment]
Fixed per rev 21757eb6f9037f852069cee97f0d23d39f2061e2
Test case added: https://github.com/clientside/amplesdk-tests/tree/master/manual/issues/171
