### ISSUE TITLE
XUL: Tabbox does not observe flex attribute.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#175]
The flex attribute on tabboxes appears to be ignored when it should be used like any other container.

Here is a test case:
http://pastebin.ca/2290937

If I put the equivalent code into XULGears in Firefox, it looks like this:
http://imagebin.org/238693

**Comment by AmicaNoctis** [comment]
Could you please checkout https://github.com/AmicaNoctis/amplesdk/commits/master and try again, whether it works now? At least your test case and my own one do with this fix.

Amica
