### ISSUE TITLE
SVG: Negative values changed to zero on tspan on IE8.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#184]
It appears that any attributes that are negative are changed to zero on tspan elements on IE8.
e.g.
http://pastebin.com/jYSmRLvY

![TransformTest](https://f.cloud.github.com/assets/1045361/113577/b8878f0a-6b63-11e2-8ab5-414264f5491d.png)

**Comment by ilinsky** [comment]
Should be fixed per 8f28e5275a14bb1bcfd4421fc5fea3759ceb06f3 Please verify. Test case has been added at https://github.com/clientside/amplesdk-tests/tree/master/manual/issues/184
