### ISSUE TITLE
Ample does not detect IE10

### ISSUE THREAD

**Issue by tedbeer** [clientside/amplesdk#188]
Ample does not detect IE10.
The following code (from ample/runtime/import.js) does not work:

```
if (!!oUADocument.namespaces) {
    bTrident    = true;
    bMSIE       = true;
    nVersion    = 1 * oUANavigator.userAgent.match(/MSIE\s(\d+\.\d+)/)[1];
}
```

I added my detecting code. See the patch in https://github.com/clientside/amplesdk/issues/187

**Comment by ilinsky** [comment]
Fixed in master: bcdf03fbc9866409d14904e7e61cf50cd23ac3f2
Fixed in mainta-0.9.4: ecb9eb8427b8c7c1991598ffa4d18bf3edf24223
