### ISSUE TITLE
transform="rotate()" does not work for HTML inside <foreignObject/> in Internet Explorer

### ISSUE THREAD

**Issue by komputist** [clientside/amplesdk#22]
If you for instance have a code like this:

<script type="application/ample+xml">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
         width="880" height="880" viewBox="0 0 880 880" >
    <foreignObject transform="rotate(32,440,440)" width="880" height="880" x="000" y="000">
      <div xmlns="http://www.w3.org/1999/xhtml" >Rotate me!</div>
    </foreignObject>
  </svg>
</script>

then, on the positive side, Internet Explorer 6-8 _will_ display the embedded XHTML. But, on the negative side, it fails to _rotate_ the embedded XHTML.

I don't know how to implement this in VML. May be (A) through re-intepreting HTML elements  as if the were VML elements? Or (B) making use of  MS filters: 
http://www.useragentman.com/blog/2010/04/05/cross-browser-animated-css-transforms-even-in-ie/
http://samuli.hakoniemi.net/cross-browser-rotation-transformation-with-css/

**Comment by clientside** [comment]
Fixed per commit fe591b7 
Problem of weird clipping is tracked in a separate issue 14
