### ISSUE TITLE
Multiple blurs instead of one

### ISSUE THREAD

**Issue by rkernahan** [clientside/amplesdk#31]
If I place 10 widgets of the same type on a page and tab from one to the next, I see a blur event on the activeWidget 10 times.
If I have 100 widgets on the page, I see 100 of the same blur events.

**Comment by clientside** [comment]
I could not reproduce the problem. Please provide a snippet.

**Comment by rkernahan** [comment]
Sent attachments by email.

**Comment by ilinsky** [comment]
The code illustrates illegal (yet not documented) practice - operating public DOM APIs on element itself from its constructor. An issue to prevent this practice opened https://github.com/clientside/amplesdk/issues/issue/32
