### ISSUE TITLE
Publish Ample SDK classes into ample namespace

### ISSUE THREAD

**Issue by rkernahan** [clientside/amplesdk#34]
How about moving the 35 AML classes from the global namespace under the ample object?
It would tidy up the global namespace and looks like it might require only minor changes to the languages.
from
     cXULElement = new AMLElement();
to
     cXULElement = new ample.AMLElement();

Low priority

**Comment by ilinsky** [comment]
I had exactly this idea since a month or so, and have scheduled the implementation for the release after 0.9.3 I do not like poluting ample object however (which is the "document" object and host for jQuery-like APIs) but would like to create a namespace for classes, maybe ample.$classes or something.

**Comment by ilinsky** [comment]
BTW, the change will likely come along with dropping "AML" prefix in classes. AMLNode->Node, AMLCustomEvent -> CustomEvent etc.

**Comment by ilinsky** [comment]
The first commit that takes all classes, markup languages element classes and attribute classes to ample.classes has landed https://github.com/clientside/amplesdk/commit/4c9ce48a59151ef340be0458e9957a54b015ef2c

For now, AMLElement can be found in ample.classes.AMLElement etc.

Renaming classes to loose AML prefix to come.

**Comment by ilinsky** [comment]
"AML" prefix has now been completely dropped and classes available in their canoncial form from ample.classes object. 
So the former global AMLElement class can now be accessed as ample.classes.Element
