### ISSUE TITLE
Ajax: Gecko returns parsererror when XML is badly formed

### ISSUE THREAD

**Issue by rkernahan** [clientside/amplesdk#45]
The success clause at 
https://github.com/clientside/amplesdk/blob/master/ample/runtime/modules/ajax.js#L28-32
calls the success callback even when Gecko returns a parsererror because the XML is not well-formed. 
Could it add a check?
if(oRequest.responseXML.documentElement && oRequest.responseXML.documentElement.tagName == "parsererror") {
  // treat as error
}

**Comment by clientside** [comment]
Good catch. 
The solution is not trivial however, and here is the problem. From the point of view of an HTTP, operation has definitely succeeded - no communication error raised. But if you match the developer intention with the result, then there was indeed an error.

To solve this jQuery have an addition parameter dataType that can be set to one of the following values: xml, json, script, or html, which would indicate what content to expect from server (much like accept-type header) and know how to process it. When no dataType specified, API would process result based on content-type HTTP header value.

The implementation of dataType settings attribute is missing from Ample SDK, will be added shortly.

**Comment by clientside** [comment]
Fixed in commit e541ec21c746f737f889
