### ISSUE TITLE
insertBefore sever problem: model out of sync with shadow

### ISSUE THREAD

**Issue by clientside** [clientside/amplesdk#49]
```
    <div id="parent" style="background-color: pink">
        <div id="child1" style="background-color: lightyellow;">1</div>
        <div id="child2" style="background-color: lightgreen;">2</div>
        <div id="child3" style="background-color: lightblue;">3</div>
    </div>
```

var parent = ample.getElementById("parent"),
child1 = ample.getElementById("child1"),
child2 = ample.getElementById("child2"),
child3 = ample.getElementById("child3");
parent.insertBefore(child1, child3);
console.log(parent.toXML());

the output is wrong: 2, 3, 1, visually is right: 2, 1, 3

**Comment by ilinsky** [comment]
Fixed in commit 3d02ee3681d156e44bab Strangely but the fix is just a revert to commit 3d095b75fbf4c927366d
