### ISSUE TITLE
README included with source downloads doesn't warn about running code from server

### ISSUE THREAD

**Issue by blacksqr** [clientside/amplesdk#5]
I'm new at using github, so when I wanted to try out Ample SDK, I clicked on the "Download source" button on the project page, and started playing with the examples.  The README file included in the archive did not warn that the example files need to be served from a server, and don't work when read by the browser right from the filesystem (i.e., I saw this: http://github.com/clientside/amplesdk/blob/master/README).  

When I mentioned this on the mailing list, I was pointed to the following version: http://github.com/clientside/amplesdk/blob/master/ample/README.  This contained helpful information, but as a beginner with github, I never would have found this file on my own.

I suggest you ensure that the version of the README with the helpful information about running from the server is included with source archive downloads, for the benefit of naive users like myself.

**Comment by clientside** [comment]
Thanks for the report. Working on that now. Hopefully I get setup that will work in the absence of PHP/.htaccess

**Comment by ilinsky** [comment]
So far did not find a way to enable running on source from file system, instead created a new detailed README document here http://github.com/clientside/amplesdk to be included with source download. Let me know if you have suggestions regarding how to improve the document.

**Comment by clientside** [comment]
Ok, I enabled running Ample SDK on source version without requiring .htaccess/PHP Web Server still required. http://github.com/clientside/amplesdk/commit/a82365eca0335219e98d43685524e1e06a99d6d2
