### ISSUE TITLE
xul:groupbox excessive margin/padding

### ISSUE THREAD

**Issue by CodaCodr** [clientside/amplesdk#53]
Ample SDK 0.9.3a18

There appears to be a large margin or padding area at the top of xul:groupbox (approx 100 pixels?)  No CSS seems able to remove it.  The test code I'm using is a groupbox containing a grid containing some labels and some textboxes.  The whole grid (my form) moves down by approx 100px.

**Comment by ilinsky** [comment]
Please check if the problem is fixed per commit d6e7ad62487880e368fb
