### ISSUE TITLE
Setting the "label" attribute on a <xul:caption> element throws an exception

### ISSUE THREAD

**Issue by dsze** [clientside/amplesdk#6]
It looks like this may be due to a typo on line #24 here:

http://github.com/clientside/amplesdk/blob/master/ample/languages/xul/elements/caption.js#L24

i.e. oElement is not defined

**Comment by ilinsky** [comment]
Good finding. Now fixed. http://github.com/clientside/amplesdk/commit/a73286a7f65cec74c68041f4a7c0e06ee5ef2dfc
