### ISSUE TITLE
Augment documentation for ample.ajax(), get() and post()

### ISSUE THREAD

**Issue by finalstep** [clientside/amplesdk#67]
The arguments to the callbacks for these functions are not documented.
The arguments are different for several scenarios: success, failure, success of non XML content.

If its helpful, here are the notes I took after experimenting and checking the source:

Missing documentation on Ajax calls
    If the data returned is not XML, the arguments to the callback are: stringData, oXHR
    If the data returned is XML, the arguments passed are: oXmlDoc, "success", oXHR
    ample.get(sUrl, data, callback, 'xml') : callback = function(document, "success", oRequest)
    amle.ajax({url: 'abc.xml', success: fSuccess, error: fError, complete: fComplete})
        \* success(sData, oXHR) for non-XML or success(oDoc, "success", oXHR) for XML
        \* error(oXHR) 
        \* complete(oXHR, "success") - even on failure the 2nd argument is always "success"!

**Comment by ilinsky** [comment]
Are you running on source?

**Comment by ilinsky** [comment]
Fixed in commit aaf999137a90d3c6ecf2
