### ISSUE TITLE
attribute value with quotes throws error

### ISSUE THREAD

**Issue by ilinsky** [clientside/amplesdk#73]
var label = ample.createElementNS(sXULNameSpace, "xul:textbox") 
label.setAttribute("value", "some text")  // works fine 
label.setAttribute("value", "\"some text\"")  // fail :(

**Comment by atrejo** [comment]
you can use this:
label.setAttribute('value', '"some text');

single quote works also on any xml around string value, like that your double quotes are interpreted as character.

**Comment by ilinsky** [comment]
Fixed per rev 4fbd537684ba3942d32a51f6f86298b2d15438aa and 2f15e4975209f471094602e279d79dc176430dfd
