### ISSUE TITLE
XML parsing error if attribute value contains ampersand

### ISSUE THREAD

**Issue by tedbeer** [clientside/amplesdk#79]
the following command fails with XML parsing error in page but without exception:
`ample.query("<span />").attr('title', '&').appendTo(ample.documentElement);
`It fails at least in FF5 and in Chrome12.

But the following works:
``` ample.query("<span />").appendTo(ample.documentElement).attr('title', '&');

```
```

**Comment by ilinsky** [comment]
Same applies to < and > characters. Also when using text() function

**Comment by 1ton** [comment]
cool issue

**Comment by ilinsky** [comment]
Fixed per rev 4fbd537684ba3942d32a51f6f86298b2d15438aa and 2f15e4975209f471094602e279d79dc176430dfd
