### ISSUE TITLE
Incorrect animation of css properties given in %

### ISSUE THREAD

**Issue by robkrueger** [clientside/amplesdk#8]
Animating left is incorrect in FF3, animating width seems to be incorrect in all browsers but IE.

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <style type="text/css">
    html, body {
      width: 100%;
      margin: 0;
    }
    .test2 {
        position: absolute;
        left: 33%;
        width: 33%;
        border: 1px solid blue;
        height: 20px;
    }
  </style>
  <script>
  function test(element) {
      ample.query(element).animate({'left' : '66%', 'width' : '66%'}, 7000, 'ease-out');
  }
  </script>
</head>

<body>
  <script type="application/ample+xml" xmlns="http://www.w3.org/1999/xhtml">
    <div style="position: relative; width: 100%; border: 1px solid red; height: 20px;">
      <div style="position: absolute; left: 33%; width: 33%; border: 1px solid blue; height: 20px;" onclick="test(this)">1</div>
    </div>
  </script>
  <script type="application/ample+xml" xmlns="http://www.w3.org/1999/xhtml">
    <div style="position: relative; width: 100%; border: 1px solid red; height: 20px;">
      <div class="test2" onclick="test(this)">2</div>
    </div>
  </script>
  <script type="text/javascript" src="/amplesdk/ample/runtime.js"></script>
  <script type="text/javascript" src="/amplesdk/ample/languages/xhtml/xhtml.js"></script>
</body>
</html>

**Comment by clientside** [comment]
Fixed in b9cc6f0
