### ISSUE TITLE
IE8 error - svg.js: style is null or not an object

### ISSUE THREAD

**Issue by darkshadow21** [clientside/amplesdk#80]
Hi guys i just started on using amples SDK and i have a problem when i use it on ie8 while the same svg file works on chrome.
It said: style is null or not an object on the svg.js line 2199.

Another problem i'm facing is that the scripts i inserted on the svg file are removed when rendered on the  page both chrome and IE.
For example i put something like this:

&lt;g onload="setInfo(evt, 'some string value')" /&gt;

And the setInfo function is on an external javascript file refrenced using an script tag like this:

&lt;script type="text/javascript" src="/interactivity.js" /&gt;

i tried setting the function inside the svg file but it doesn't work too.

Can anyone help me?

Thanks in advance.

Eduardo

**Comment by ilinsky** [comment]
1) style is null or not an object on the svg.js line 2199.
Could you provide with the test case? Keep in mind that style object is not exposed in Ample SDK

2) Another problem i'm facing is that the scripts i inserted on the svg file
Can you try putting external script outside SVG content? (I see only inline content in script can work, but externally referenced scripts are not processed, when specified within SVG content. TODO)

**Comment by ilinsky** [comment]
Closing as there have been no requested information communicated.
