### ISSUE TITLE
method attr("id","value") does not work

### ISSUE THREAD

**Issue by abudaan** [clientside/amplesdk#81]
If you create an svg object an query the created object, it is not possible to use the attr("id","value") method of that object.

code:

&lt;circle id="circle" cx="200" cy="200" r="10" fill="red" opacity="1" stroke="black" stroke-width="1"&gt;

var c = ample.query("circle");

c.attr("fill","green");

This does not work in any browser

**Comment by ilinsky** [comment]
Fixed in rev 7eb1cd76a5a2c8b15e8b
