### ISSUE TITLE
ample.query does not accept Query object as context

### ISSUE THREAD

**Issue by tedbeer** [clientside/amplesdk#83]
in jQuery the following code works:
```var divs = jQuery('div');
var imgs = jQuery('img', divs);

``````
In AmpleSDK ample.query accepts only Node as context and does not accept Query object.
So the code following code fails:
```var divs = ample.query('div');
var imgs = ample.query('img', divs);
``````

**Comment by ilinsky** [comment]
Fixed per rev 5c2e080af32738a0bfca
