### ISSUE TITLE
Dynamic xinclude duplicates question mark ('?') in href url.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#84]
If I'm appending some xml with an xinclude in it, ample appears to duplicate the question mark in the url.

e.g.:
js snippet:
var newNode = ample.importNode(resultXML.documentElement,true);
ample.query("#main").append(newNode);

resultXML snippet:
<xi:include href="?type=xul&amp;object=home&amp;part=messages" />

If I run the above code, I get this message in my log:
XHR finished loading: "http://localhost/??type=xul&object=home&part=messages".

This means that the 'type' variable passed becomes the '?type' variable.

**Comment by ilinsky** [comment]
Fixed in rev 31670200bd
