### ISSUE TITLE
XUL: Cannot specify :hover class on box or its derivations.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#86]
For some reason, when using css: 
.mybox { background-color: white; } 
works, but 
.mybox:hover {background-color: blue;} 
doesn't.

This appears not to work where the .mybox class matches a box, vbox, or hbox element.

**Comment by ilinsky** [comment]
The reason why :hover pseudo-class doesn't work on some XUL elements is performance optimization. You can tweak the hover effect on XUL elements by defining its XULElement class prototype (or you can choose to tweak specific elements you need in the same fashion) to have $hoverable property set to true.

**Comment by ilinsky** [comment]
You can tweak behavior in the application sources, rather than in sources of AMple SDK by doing following: ample.classes["http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul##element"].prototype.$hoverable = true;
