### ISSUE TITLE
XUL: display:block inside box should wrap.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#87]
In the below XUL script, the boxes with a width of 100px should wrap and expand the parent box vertically because their combined width is greater than the max-width of 500px.  This works in XUL Gear in Firefox.  In Ample, currently the child boxes are all laid out horizontally and break out of the parent box.

Test case: http://pastebin.com/jHpN5XP6

**Comment by ilinsky** [comment]
Will not be fixed, as XUL box/hbox/vbox element are designed (and implemented in a complex way) to be display:flexbox. Unfortunately in Ample SDK you cannot change this behavior for flex box elements. 
You may consider using XHTML div element instead if you need different kind of layout.
