### ISSUE TITLE
XUL: Script tag does not decode entities.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#89]
The xul:script tag when using the src attribute does not convert entities to their equivalent.

e.g. &lt;xul:script src="?key1=value1&amp;amp;key2=value2" /&gt;
results in the url ?key1=value1&amp;amp;key2=value2 being called, when the url
?key1=value1&amp;key2=value2 
should have been called.

**Comment by h6w** [comment]
I have modified languages/xul/elements/script.js to make this work in my fork.

**Comment by ilinsky** [comment]
Fixed per rev fb7469f9fa
