### ISSUE TITLE
Empty TD added to DOM by XUL API

### ISSUE THREAD

**Issue by CodaCodr** [clientside/amplesdk#9]
It seems that appending an empty xul:treerow will cause a blank TD to be inserted into the underlying DOM.  See this post on the Amp0le SDK forum:

http://groups.google.com/group/amplesdk/t/ccfbdfa8a0da30e3

Note: I'm guessing at the cause!

**Comment by clientside** [comment]
Fixed in http://github.com/clientside/amplesdk/commit/ceef3e0e701764b4b205d03dc7cf2ee6b6878007
