### ISSUE TITLE
XUL: query.insertBefore() and node.insertBefore() fail with toolbars.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#91]
fElement_insertBefore() appears to fail with toolbars.

e.g. This script should insert incrementing buttons between button 1 and button 2.

http://pastebin.com/XkGivWj1

Instead we get a number of errors in the console.

**Comment by ilinsky** [comment]
Fixed per rev 668b862032. Test case: https://github.com/clientside/amplesdk-tests/blob/master/manual/issues/091/index.html 
Please note that jQuery alternative to DOM insertBefore() is before()

**Comment by h6w** [comment]
Yes.  I was using before() and noticed that it's a convenience call for insertBefore(), so I checked to make sure that insertBefore() worked before logging an issue against before(). :-p
