### ISSUE TITLE
XUL: insertBefore() and toolbarspacer inserts off by one.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#92]
When inserting a toolbarbutton into a toolbar using the node.insertBefore() or query.insertBefore() methods, and the node reference is a toolbarspacer, the button is inserted correctly into the ample document, but is off by one in the html document.

e.g. http://pastebin.com/tJsUgxHL

In this example, the button should be inserted before the toolbarspacer, and result in all inserted buttons bunched towards "start".  Instead, the buttons are inserted to the right of the spacer and are bunched up towards "end".

The console log shows that the resulting ample DOM is correct, however, the html is incorrect.

**Comment by ilinsky** [comment]
In Ample SDK there is toolbarspacer element implemented. This is the reason why test page renders with a JavaScript error (see console), not to say it doesn't work properly later. Also, as per https://developer.mozilla.org/en/XUL/toolbarspacer "A space between toolbar items" Neither does Ample SDK have support for toolbaritem elements.

If in the attached testcase I replace toolbarspacer with toolbarseparator, the supposedly faulty behavior put in the report does not appear.

Do you need support for toolbaritem and toolbarspacer elements? If so, please open a separate feature request!

**Comment by ilinsky** [comment]
Test case: https://github.com/clientside/amplesdk-tests/blob/master/manual/issues/092/index.html
